authapp/urls.py
from django.urls import path
from .views import edit, dashboard, register,form_submission,index
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
                                       PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetDoneView)
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'authapp'

urlpatterns = [
    path('',index,name='index'),
    path('register/', register, name='register'),
    #  path('form/', views.form_submission, name='form'),
    path('edit/', edit, name='edit'),
    path('dashboard/', dashboard, name='dashboard'),
    path('dashboard/form', form_submission, name='form'),
    path('dashboard/submit-form/', views.form_submission, name='form_submission'),
    path('dashboard/proposal/inbox/', views.proposal_inbox, name='proposal_inbox'),
    path('dashboard/status/', views.status_page, name='status_page'),
    path('dashboard/save/', views.save_page, name='save_page'),
    path('dashboard/form-details/<str:reference_number>/', views.form_details, name='form_details'),
    path('dashboard/success/', views.success_page, name='success_page'),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='authapp/logged_out.html'), name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='authapp/password_change_form.html'), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='authapp/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='authapp/password_reset_form.html',
        email_template_name='authapp/password_reset_email.html',
        success_url=reverse_lazy('authapp:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='authapp/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='authapp/password_reset_confirm.html',
        success_url=reverse_lazy('authapp:login')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='authapp/password_reset_complete.html'), name='password_reset_complete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('authapp.urls', namespace='authapp')),
    path('admin/', admin.site.urls),
]

authapp/forms.py
from django.contrib.auth.models import User
from django import forms
# from .models import Profile
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from .models import UserRegistrationModel
from django.contrib.auth.forms import PasswordResetForm
from django import forms
# from .models import FormData


class UserRegistration(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('Passwords don\'t match.')
            return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

# from django import forms


from django import forms
from .models import FormSubmission

class FormSubmissionForm(forms.ModelForm):
    class Meta:
        model = FormSubmission
        fields = '__all__'

authapp/views.py
from django.http import request
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import UserRegistration, UserEditForm
from .forms import FormSubmissionForm

# Create your views here.

def index(request):
    return render(request,'authapp/index.html')

@login_required
def dashboard(request):
    context = {
        "welcome": "Welcome to your dashboard"
    }
    return render(request, 'authapp/dashboard.html', context=context)


def register(request):
    if request.method == 'POST':
        form = UserRegistration(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(
                form.cleaned_data.get('password')
            )
            new_user.save()
            return render(request, 'authapp/register_done.html')
    else:
        form = UserRegistration()

    context = {
        "form": form
    }

    return render(request, 'authapp/register.html', context=context)


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        if user_form.is_valid():
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
    context = {
        'form': user_form,
    }
    return render(request, 'authapp/edit.html', context=context)


# from django.shortcuts import render, redirect

# change my complete views.py accordingly
# views.py
from django.shortcuts import render, redirect
from .models import FormSubmission
from .forms import FormSubmissionForm

@login_required
def form_submission_view(request):
    if request.method=='POST':
        form = FormSubmissionForm(request.POST, request.FILES)
        if form.is_valid():
            # Save the form data to the database
            form.save()
            return redirect('success_page')
    else:
        form = FormSubmissionForm()

    return render(request, 'authapp/form.html', {'form': form})

# @login_required
# def form_submission(request):
#     if request.method == 'POST':
#         uname = request.POST.get('uname')
#         name = request.POST.get('name')
#         dob = request.POST.get('dob')
#         mobile = request.POST.get('mobile')
#         gender = request.POST.get('gender')
#         nationality = request.POST.get('nationality')
#         # Continue to get other form field values
   
     
#       # Biodata and Photo Details
#         biodata = request.FILES.get('biodata')
#         photo = request.FILES.get('photo')

#     # Father/Spouse Details
#         father_spouse = request.POST.get('father_spouse')

#     # Expertise Area
#         expertise = request.POST.get('expertise')

#     # Personal Address Details
#         address1 = request.POST.get('address1')
#         address2 = request.POST.get('address2')
#         city = request.POST.get('city')
#         district = request.POST.get('district')
#         state = request.POST.get(' state')
#         pincode = request.POST.get('pincode')

#     # Institution Details
#         inst_state = request.POST.get('inst_state')
#         inst_district = request.POST.get(' inst_district')
#         institution = request.POST.get(' institution')
#         designation = request.POST.get(' designation')
#         department = request.POST.get('department')

#     # Qualifying Degree
#         QUALIFYING_DEGREE_CHOICES = (
#         ('M.S.', 'M.S.'),
#         ('M.D.', 'M.D.'),
#         ('PhD', 'PhD'),
#         )
#         qualifying_degree = request.POST.get('qualifying_degree')
#         degree_awarded = request.POST.get(' degree_awarded')
#         degree_date = request.POST.get(' degree_date')

#     # Thesis Title and Subject
#         thesis_title = request.POST.get('thesis_title')
#         subject = request.POST.get('subject')

#     # Research Supervisor/Guide and University/Institute
#         supervisor_guide = request.POST.get('supervisor_guide')
#         university_institute = request.POST.get('university_institute')

#     # Brief Details of Research Work
#         research_work_details = request.POST.get('research_work_details')

#     # Proposed Research Details
#         project_title = request.POST.get('project_title')
#         project_summary = request.POST.get('project_summary')
#         keywords = request.POST.get('keywords')
#         objectives = request.POST.get('objective')
#         result = request.POST.get('result')
#         methodology_work_plan = request.FILES.get('methodology_work_plan')

#     # Mentor Details
#         mentor_institute = request.POST.get('mentor_institute')
#         mentor_email = request.POST.get(' mentor_email')
#         mentor_name = request.POST.get('mentor_name')
#         registrar_email = request.POST.get('registrar_email')
#         phd_scholars_working = request.POST.get('phd_scholars_working')
#         postdoc_fellows_working = request.POST.get('postdoc_fellows_working')
    
#     # Upload
#         Undertaking = request.FILES.get('Undertaking')
#         Endorsement = request.FILES.get('Endorsement')
#         Birth = request.FILES.get('Birth')
#         CV= request.FILES.get('CV')
#         Plagiarism = request.FILES.get('Plagiarism')
#         Pub2 = request.FILES.get('Best Publication-2')
#         Caste = request.FILES.get('Caste')
#         Degree= request.FILES.get('Degree')
#         thesis = request.FILES.get('thesis')
#         Pub1 = request.FILES.get('Best Publication-1')
    
#     # Reference Details
#         reference1_name_address = request.POST.get('reference1_name_address')
#         reference1_email = request.POST.get('reference1_email')
#         reference1_contact = request.POST.get('reference1_contact')
#         reference2_name_address = request.POST.get('reference2_name_address')
#         reference2_email = request.POST.get('reference2_email')
#         reference2_contact = request.POST.get('reference2_contact')
    
#         form_submission = FormSubmission(
#             uname=uname,
#             name=name,
#             dob=dob,
#             mobile=mobile,
#             gender=gender,
#             nationality=nationality,biodata=biodata,
#             photo=photo,
#             father_spouse=father_spouse,expertise=expertise,
#             address1=address1,
#             address2=address2,
#             city=city,district=district,
#             state=state,pincode=pincode,
#             inst_state=inst_state,
#             inst_district=inst_district,
#             institution=institution,
#             designation=designation,
#             department= department,
#             qualifying_degree = qualifying_degree ,
#             degree_awarded=degree_awarded,
#             degree_date=degree_date,
#             thesis_title=thesis_title,
#             subject=subject,supervisor_guide=supervisor_guide,university_institute=university_institute,
#             research_work_details=research_work_details,project_title=project_title,
#             project_summary=project_summary,keywords=keywords,objectives=objectives,
#             result=result,methodology_work_plan=methodology_work_plan,
#             mentor_institute=mentor_institute,
#             mentor_name=mentor_name,
#             mentor_email=mentor_email,
#             registrar_email=registrar_email,
#             phd_scholars_working=phd_scholars_working,postdoc_fellows_working=postdoc_fellows_working,
#             Undertaking=Undertaking,
#             Endorsement=Endorsement,Birth=Birth,
#             CV=CV,Plagiarism=Plagiarism,Pub1=Pub1,Pub2=Pub2,Caste=Caste,Degree=Degree,
#             thesis=thesis,
#             reference1_name_address=reference1_name_address,
#             reference1_email=reference1_email,reference1_contact=reference1_contact,
#             reference2_name_address=reference2_name_address,reference2_email=reference2_email,
#             reference2_contact=reference2_contact



            
#             # Set other attributes here based on the form data
#         )
#         form_submission.save()
#         return redirect('authapp:dashboard')
#     return render(request, 'authapp/form.html')

# def success_page(request):
#     render(request, 'authapp/success.html')

# views.py

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import FormSubmission
from django.utils.crypto import get_random_string

@login_required
def form_submission(request):
    if request.method == 'POST':
        # Process form submission and save the data
        uname = request.POST.get('uname')
        name = request.POST.get('name')
        dob = request.POST.get('dob')
        mobile = request.POST.get('mobile')
        gender = request.POST.get('gender')
        nationality = request.POST.get('nationality')
        father_spouse = request.POST.get('father_spouse')
        expertise = request.POST.get('expertise')
        address1 = request.POST.get('address1')
        address2 = request.POST.get('address2')
        city = request.POST.get('city')
        district = request.POST.get('district')
        state = request.POST.get('state')
        pincode = request.POST.get('pincode')
        inst_state = request.POST.get('inst_state')
        inst_district = request.POST.get('inst_district')
        institution = request.POST.get('institution')
        designation = request.POST.get('designation')
        department = request.POST.get('department')
        qualifying_degree = request.POST.get('qualifying_degree')
        degree_awarded = request.POST.get('degree_awarded')
        degree_date = request.POST.get('degree_date')
        thesis_title = request.POST.get('thesis_title')
        subject = request.POST.get('subject')
        supervisor_guide = request.POST.get('supervisor_guide')
        university_institute = request.POST.get('university_institute')

authapp/templates/authapp/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Dashboard</title>
  <link rel="stylesheet" href="{% static 'css/style1.css' %}">
  <!-- <link rel="stylesheet" href="{% static 'authapp/static/css/style.css' %}"> -->
  

</head>

<body>
  <!-- partial:index.partial.html -->
  ​<!-- Box icon CSS   -->
  <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
  <!-- End -->
  <!-- {% include "navbar.html" %} -->

  <div class="sidebar close">
    <div class="logo-details">

      <a href="#">
        <i class='bx bx-home'></i>
      </a>
      <span class="logo_name">Serb Online Home </span>


    </div>
    <ul class="nav-links">
      <li>
        <div class="icon-link">
          <a href="#">
            <i class='bx bx-file'></i>
            <span class="link_name">Proposal</span>
          </a>
          <i class='bx bxs-chevron-down arrow'></i>
        </div>
        <ul class="sub-menu">
          <li><a class="link_name" href="#">Proposal Submission</a></li>

          <li>

            <a href="{% url 'authapp:form' %}">Form Submisison</a>
          </li>
          <li><a href="#">Saved Proposal</a></li>
          <li><a href="{% url 'authapp:proposal_inbox' %}">View Submitted Proposals</a></li>
        </ul>
      </li>
      <li>
        <div class="icon-link">
          <a href="#">
            <i class='bx bxs-credit-card'></i>
            <span class="link_name">RTGS/Quotations</span>
          </a>
          <i class='bx bxs-chevron-down arrow'></i>
        </div>
        <ul class="sub-menu">
          <li><a class="link_name" href="#">RTGS/Quotations</a></li>
          <li><a href="#">Upload</a></li>
        </ul>
      </li>
      <li>
        <div class="icon-link">
          <a href="#">
            <i class='bx bx-news'></i>
            <span class="link_name">Requests</span>
          </a>
          <i class='bx bxs-chevron-down arrow'></i>
        </div>
        <ul class="sub-menu">
          <li><a class="link_name" href="#">Requests</a></li>
          <li><a href="#">Request Sent</a></li>
          <li><a href="#">Submit Document</a></li>
          <li><a href="#">Request for change of institute after release</a></li>
          <li><a href="#">Miscellaneous Request</a></li>
        </ul>
      </li>
      <li>
        <div class="icon-link">
          <a href="#">
            <i class='bx bx-user'></i>
            <span class="link_name">User Profile</span>
          </a>
          <i class='bx bxs-chevron-down arrow'></i>
        </div>
        <ul class="sub-menu">
          <li><a class="link_name" href="#">User Profile</a></li>
          <li><a href="#">
              Profile Detail</a></li>
          <li><a href="#">Profile Other Detail</a></li>
          <li><a href="#">View Fill Profile</a></li>
          <li><a href="#">Funded Projects </a></li>
          <li><a href="#">Change Password</a></li>
        </ul>
      </li>



    </ul>

    <li>
      <div class="profile-details">
        <!-- <div class="profile-content">
            <img src="" alt="profileImg">
          </div> -->
        <div></div>

        <div class="name-job">
          <div class="profile_name"> <b> Welcome {{user.first_name}}</b></div>
        </div>
        <a href="{% url 'authapp:logout' %}"><i class='bx bx-log-out' style="color:white;"></i></a>

      </div>
    </li>
    </ul>
  </div>
  <section class="home-section">
    <div class="home-content">
      <i class='bx bx-menu' style="color: black;font:bolder; "> </i>

      <!-- Right section of the sidemenu -->
      <div class="right-section">
        <h1 class="serb-heading">Science and Engineering Research Board</h1>
        <p class="serb-details">
        <div>(Statutory Body Established Through an Act of Parliament: SERB Act 2008)</div>
        <div >Government of India</div>
        </p>
      </div>
    </div>
  </section>
  <div>



    <!-- partial -->
    <script src="{%static 'javascript/script.js' %}"></script>

</body>

</html>

authapp/templates/authapp/edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Edit{% endblock title %}
{% block content %}
<h2>Edit your account</h2>
<p>You can edit your account using the follow form</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

authapp/templates/authapp/form_details.html
<!-- form_details.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Form Details</title>
</head>
<body>
    <h1>Form Details</h1>
    <p>Reference Number: {{ form_submission.reference_number }}</p>
    <p>Status: {{ form_submission.status }}</p>
    <!-- Display all other form fields here -->
</body>
</html>

authapp/templates/authapp/password_change_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<h2>Change Your Password</h2>
<p>Use the form below to change your Password</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

authapp/templates/authapp/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Password reset{% endblock %}
{% block content %}
<h2>Password set</h2>
<p>Your password has been set. You can
    <a href="{% url 'authapp:login' %}">log in now</a></p>
{% endblock %}

authapp/templates/authapp/password_reset_confirm.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>
{% if validlink %}
<p>Please enter your new password twice:</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary" value="Change my password">Submit</button>
    {% endbuttons %}
</form>
{% else %}
<p>The password reset link was invalid, possibly because it has
    already been used. Please request a new password reset.</p>
{% endif %}
{% endblock %}

authapp/templates/authapp/password_reset_done.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>
<p>We've emailed you instructions for setting your password.</p>
<p>If you don't receive an email, please make sure you've entered
    the address you registered with.</p>
{% endblock %}

authapp/templates/authapp/password_reset_email.html
Someone asked for password reset for email {{email}}.Follow the Link below
{{ protocol }}://{{ domain }}{% url "authapp:password_reset_confirm"
uidb64=uid token=token %}

authapp/templates/authapp/password_reset_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Reset your password

{% endblock title %}
{% block content %}
<div class="container">
    <h2>Forgotten your Password</h2>
    <p>Enter your email address to obtain a new password</p>
    <form action="" method="post" class="form ">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary" value="send e-mail">Submit</button>
        {% endbuttons %}
    </form>
</div>
{% endblock content %}

authapp/templates/authapp/proposal_inbox.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Proposal Inbox</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/style1.css' %}">
</head>

<body>
    <div class="container mt-4">
        <div class="home-content">
            <i class='bx bx-menu' style="color: black;font:bolder; "> </i>
      
            <!-- Right section of the sidemenu -->
            <div class="right-section">
              <h1 class="serb-heading">Science and Engineering Research Board</h1>
              <p class="serb-details">
              <div>(Statutory Body Established Through an Act of Parliament: SERB Act 2008)</div>
              <div >Government of India</div>
              </p>
            </div>
          </div>
    </div>
  <div class="container mt-5">
    <h2 class="mb-4">Proposal Inbox</h2>
    <div class="table-responsive">
      <table class="table table-bordered table-hover">
        <thead class="thead-dark">
          <tr>
            <th>Reference Number</th>
            <th>Name</th>
            <th>Institute</th>
            <th>Submission Date</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {% for proposal in proposals %}
          <tr>
            <td>{{ proposal.reference_number }}</td>
            <td>{{ proposal.name }}</td>
            <td>{{ proposal.institution  }}</td>
            <td>{{ proposal.created_date }}</td>
            
                <td style="color: {% if proposal.status == 'Pending' %}red{% else %}green{% endif %};">{{ proposal.status }}</td>
            
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <!-- Bootstrap JS (optional, only if you need JS functionality) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

authapp/templates/authapp/register.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Registration

{% endblock title %}
{% block content %}

{% if form.errors %}
    
{% endif %}
    
<form action="" method="post" class="form container">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

authapp/templates/authapp/register_done.html
{% extends "base.html" %}
{% block content %}
<h1>Welcome {{ new_user.first_name }}!</h1>
<p>Your account has been successfully created. Now you can <a href="{% url 'authapp:login' %}">log in</a>.</p>
{% endblock content %}

authapp/templates/authapp/save.html
<!-- save.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Saved Forms</title>
</head>
<body>
    <h1>Saved Forms</h1>
    <ul>
        {% for form_submission in saved_forms %}
        <li>
            <a href="{% url 'form_details' form_submission.reference_number %}">
                Reference Number: {{ form_submission.reference_number }}
            </a> | Status: {{ form_submission.status }}
        </li>
        {% endfor %}
    </ul>
</body>
</html>