authapp/urls.py
from django.urls import path
from .views import edit, dashboard, register,form_submission,index
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
                                       PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetDoneView)
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'authapp'

urlpatterns = [
    path('',index,name='index'),
    path('register/', register, name='register'),
    #  path('form/', views.form_submission, name='form'),
    path('edit/', edit, name='edit'),
    path('dashboard/', dashboard, name='dashboard'),
    path('dashboard/form', form_submission, name='form'),
    path('dashboard/submit-form/', views.form_submission, name='form_submission'),
    path('dashboard/proposal/inbox/', views.proposal_inbox, name='proposal_inbox'),
    path('dashboard/status/', views.status_page, name='status_page'),
    path('dashboard/save/', views.save_page, name='save_page'),
    path('dashboard/form-details/<str:reference_number>/', views.form_details, name='form_details'),
    path('dashboard/success/', views.success_page, name='success_page'),
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='authapp/logged_out.html'), name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='authapp/password_change_form.html'), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='authapp/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='authapp/password_reset_form.html',
        email_template_name='authapp/password_reset_email.html',
        success_url=reverse_lazy('authapp:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='authapp/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='authapp/password_reset_confirm.html',
        success_url=reverse_lazy('authapp:login')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='authapp/password_reset_complete.html'), name='password_reset_complete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('authapp.urls', namespace='authapp')),
    path('admin/', admin.site.urls),
]

authapp/forms.py
from django.contrib.auth.models import User
from django import forms
# from .models import Profile
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from .models import UserRegistrationModel
from django.contrib.auth.forms import PasswordResetForm
from django import forms
# from .models import FormData


class UserRegistration(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('Passwords don\'t match.')
            return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

# from django import forms


from django import forms
from .models import FormSubmission

class FormSubmissionForm(forms.ModelForm):
    class Meta:
        model = FormSubmission
        fields = '__all__'

authapp/views.py
from django.http import request
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import UserRegistration, UserEditForm
from .forms import FormSubmissionForm

# Create your views here.

def index(request):
    return render(request,'authapp/index.html')

@login_required
def dashboard(request):
    context = {
        "welcome": "Welcome to your dashboard"
    }
    return render(request, 'authapp/dashboard.html', context=context)


def register(request):
    if request.method == 'POST':
        form = UserRegistration(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(
                form.cleaned_data.get('password')
            )
            new_user.save()
            return render(request, 'authapp/register_done.html')
    else:
        form = UserRegistration()

    context = {
        "form": form
    }

    return render(request, 'authapp/register.html', context=context)


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        if user_form.is_valid():
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
    context = {
        'form': user_form,
    }
    return render(request, 'authapp/edit.html', context=context)


# from django.shortcuts import render, redirect

# change my complete views.py accordingly
# views.py
from django.shortcuts import render, redirect
from .models import FormSubmission
from .forms import FormSubmissionForm

@login_required
def form_submission_view(request):
    if request.method=='POST':
        form = FormSubmissionForm(request.POST, request.FILES)
        if form.is_valid():
            # Save the form data to the database
            form.save()
            return redirect('success_page')
    else:
        form = FormSubmissionForm()

    return render(request, 'authapp/form.html', {'form': form})

# @login_required
# def form_submission(request):
#     if request.method == 'POST':
#         uname = request.POST.get('uname')
#         name = request.POST.get('name')
#         dob = request.POST.get('dob')
#         mobile = request.POST.get('mobile')
#         gender = request.POST.get('gender')
#         nationality = request.POST.get('nationality')
#         # Continue to get other form field values
   
     
#       # Biodata and Photo Details
#         biodata = request.FILES.get('biodata')
#         photo = request.FILES.get('photo')

#     # Father/Spouse Details
#         father_spouse = request.POST.get('father_spouse')

#     # Expertise Area
#         expertise = request.POST.get('expertise')

#     # Personal Address Details
#         address1 = request.POST.get('address1')
#         address2 = request.POST.get('address2')
#         city = request.POST.get('city')
#         district = request.POST.get('district')
#         state = request.POST.get(' state')
#         pincode = request.POST.get('pincode')

#     # Institution Details
#         inst_state = request.POST.get('inst_state')
#         inst_district = request.POST.get(' inst_district')
#         institution = request.POST.get(' institution')
#         designation = request.POST.get(' designation')
#         department = request.POST.get('department')

#     # Qualifying Degree
#         QUALIFYING_DEGREE_CHOICES = (
#         ('M.S.', 'M.S.'),
#         ('M.D.', 'M.D.'),
#         ('PhD', 'PhD'),
#         )
#         qualifying_degree = request.POST.get('qualifying_degree')
#         degree_awarded = request.POST.get(' degree_awarded')
#         degree_date = request.POST.get(' degree_date')

#     # Thesis Title and Subject
#         thesis_title = request.POST.get('thesis_title')
#         subject = request.POST.get('subject')

#     # Research Supervisor/Guide and University/Institute
#         supervisor_guide = request.POST.get('supervisor_guide')
#         university_institute = request.POST.get('university_institute')

#     # Brief Details of Research Work
#         research_work_details = request.POST.get('research_work_details')

#     # Proposed Research Details
#         project_title = request.POST.get('project_title')
#         project_summary = request.POST.get('project_summary')
#         keywords = request.POST.get('keywords')
#         objectives = request.POST.get('objective')
#         result = request.POST.get('result')
#         methodology_work_plan = request.FILES.get('methodology_work_plan')

#     # Mentor Details
#         mentor_institute = request.POST.get('mentor_institute')
#         mentor_email = request.POST.get(' mentor_email')
#         mentor_name = request.POST.get('mentor_name')
#         registrar_email = request.POST.get('registrar_email')
#         phd_scholars_working = request.POST.get('phd_scholars_working')
#         postdoc_fellows_working = request.POST.get('postdoc_fellows_working')
    
#     # Upload
#         Undertaking = request.FILES.get('Undertaking')
#         Endorsement = request.FILES.get('Endorsement')
#         Birth = request.FILES.get('Birth')
#         CV= request.FILES.get('CV')
#         Plagiarism = request.FILES.get('Plagiarism')
#         Pub2 = request.FILES.get('Best Publication-2')
#         Caste = request.FILES.get('Caste')
#         Degree= request.FILES.get('Degree')
#         thesis = request.FILES.get('thesis')
#         Pub1 = request.FILES.get('Best Publication-1')
    
#     # Reference Details
#         reference1_name_address = request.POST.get('reference1_name_address')
#         reference1_email = request.POST.get('reference1_email')
#         reference1_contact = request.POST.get('reference1_contact')
#         reference2_name_address = request.POST.get('reference2_name_address')
#         reference2_email = request.POST.get('reference2_email')
#         reference2_contact = request.POST.get('reference2_contact')
    
#         form_submission = FormSubmission(
#             uname=uname,
#             name=name,
#             dob=dob,
#             mobile=mobile,
#             gender=gender,
#             nationality=nationality,biodata=biodata,
#             photo=photo,
#             father_spouse=father_spouse,expertise=expertise,
#             address1=address1,
#             address2=address2,
#             city=city,district=district,
#             state=state,pincode=pincode,
#             inst_state=inst_state,
#             inst_district=inst_district,
#             institution=institution,
#             designation=designation,
#             department= department,
#             qualifying_degree = qualifying_degree ,
#             degree_awarded=degree_awarded,
#             degree_date=degree_date,
#             thesis_title=thesis_title,
#             subject=subject,supervisor_guide=supervisor_guide,university_institute=university_institute,
#             research_work_details=research_work_details,project_title=project_title,
#             project_summary=project_summary,keywords=keywords,objectives=objectives,
#             result=result,methodology_work_plan=methodology_work_plan,
#             mentor_institute=mentor_institute,
#             mentor_name=mentor_name,
#             mentor_email=mentor_email,
#             registrar_email=registrar_email,
#             phd_scholars_working=phd_scholars_working,postdoc_fellows_working=postdoc_fellows_working,
#             Undertaking=Undertaking,
#             Endorsement=Endorsement,Birth=Birth,
#             CV=CV,Plagiarism=Plagiarism,Pub1=Pub1,Pub2=Pub2,Caste=Caste,Degree=Degree,
#             thesis=thesis,
#             reference1_name_address=reference1_name_address,
#             reference1_email=reference1_email,reference1_contact=reference1_contact,
#             reference2_name_address=reference2_name_address,reference2_email=reference2_email,
#             reference2_contact=reference2_contact



            
#             # Set other attributes here based on the form data
#         )
#         form_submission.save()
#         return redirect('authapp:dashboard')
#     return render(request, 'authapp/form.html')

# def success_page(request):
#     render(request, 'authapp/success.html')

# views.py

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import FormSubmission
from django.utils.crypto import get_random_string

@login_required
def form_submission(request):
    if request.method == 'POST':
        # Process form submission and save the data
        uname = request.POST.get('uname')
        name = request.POST.get('name')
        dob = request.POST.get('dob')
        mobile = request.POST.get('mobile')
        gender = request.POST.get('gender')
        nationality = request.POST.get('nationality')
        father_spouse = request.POST.get('father_spouse')
        expertise = request.POST.get('expertise')
        address1 = request.POST.get('address1')
        address2 = request.POST.get('address2')
        city = request.POST.get('city')
        district = request.POST.get('district')
        state = request.POST.get('state')
        pincode = request.POST.get('pincode')
        inst_state = request.POST.get('inst_state')
        inst_district = request.POST.get('inst_district')
        institution = request.POST.get('institution')
        designation = request.POST.get('designation')
        department = request.POST.get('department')
        qualifying_degree = request.POST.get('qualifying_degree')
        degree_awarded = request.POST.get('degree_awarded')
        degree_date = request.POST.get('degree_date')
        thesis_title = request.POST.get('thesis_title')
        subject = request.POST.get('subject')
        supervisor_guide = request.POST.get('supervisor_guide')
        university_institute = request.POST.get('university_institute')

authapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    
        <!-- CSS -->
    <!-- <link rel="stylesheet" href="{% static 'authapp/static/css/style.css' %}"> -->
    <link rel="stylesheet" href="{% static 'authapp/static/css/style1.css' %}">


    <title>App {% block title %}{% endblock title %}</title>
</head>

<body>
    {% include "navbar.html" %}
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>

    
</body>

</html>

authapp/templates/home.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock title %}
{% block content %}
<h1>{{welcome}}</h1>
<br>
<a href="{% url 'authapp:edit' %}" class="btn btn-primary">Edit Your Profile</a> or
<a href="{% url 'authapp:password_change' %}" class="btn btn-warning">Change your password</a>
<hr>
{% end content %}

authapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="">Authentication <i class="fas fa-boxes"></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        {% if request.user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'authapp:dashboard' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="#">Dashboard</a>
            </li>
        </ul>
        {% endif %}
        <span>
            {% if request.user.is_authenticated %}
            <a href="{% url 'authapp:logout' %}" class="btn btn-danger">Logout</a>
            Hello
            @ <i>{{user.username}}</i>
            {% else %}
            <div class="login__left">
                <a href="{% url 'authapp:login' %}" class="btn btn-secondary">Log-in</a>
                <a href="{% url 'authapp:register' %}" class="btn btn-info ">Register</a>
            </div>

            {% endif %}

        </span>
    </div>
</nav>